"""initial schema

Revision ID: 7358f0a5b411
Revises: 
Create Date: 2026-06-20 13:36:53.346213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7358f0a5b411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lng', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('ghana_card_number', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("role IN ('user', 'admin')", name='chk_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('admin_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("action_type IN ('approve_pro','reject_pro','suspend_user','resolve_dispute','refund_payment','override_status')", name='chk_admin_action_type'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geocode_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lat_key', sa.String(length=12), nullable=False),
    sa.Column('lng_key', sa.String(length=12), nullable=False),
    sa.Column('resolved_city', sa.String(length=100), nullable=False),
    sa.Column('resolved_area', sa.String(length=150), nullable=True),
    sa.Column('location_index_id', sa.UUID(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['location_index_id'], ['location_index.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_key', 'lng_key', name='uq_geocode_coords')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("type IN ('new_quote','quote_accepted','booking_confirmed','booking_reminder','review_received','pro_approved','booking_cancelled','payment_received','payout_sent')", name='chk_notification_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=220), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('certificate_url', sa.Text(), nullable=True),
    sa.Column('ghana_card_url', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('availability_note', sa.String(length=255), nullable=True),
    sa.Column('base_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("verification_status IN ('pending','approved','rejected','suspended')", name='chk_pro_verification_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('service_subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('location_index_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('gps_captured', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_index_id'], ['location_index.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_categories',
    sa.Column('pro_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pro_id'], ['pro_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pro_id', 'category_id')
    )
    op.create_table('pro_service_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pro_id', sa.UUID(), nullable=True),
    sa.Column('location_index_id', sa.UUID(), nullable=True),
    sa.Column('radius_km', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_index_id'], ['location_index.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pro_id'], ['pro_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pro_subcategories',
    sa.Column('pro_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pro_id'], ['pro_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['service_subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pro_id', 'subcategory_id')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('location_index_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('location_from_gps', sa.Boolean(), nullable=True),
    sa.Column('budget_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('preferred_time_slot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("preferred_time_slot IN ('morning','afternoon','evening','flexible')", name='chk_request_time_slot'),
    sa.CheckConstraint("status IN ('open','matched','in_progress','completed','cancelled','expired')", name='chk_request_status'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_index_id'], ['location_index.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['service_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('pro_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('available_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','rejected','withdrawn','expired')", name='chk_quote_status'),
    sa.ForeignKeyConstraint(['pro_id'], ['pro_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'pro_id', name='uq_one_quote_per_pro_per_request')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('pro_id', sa.UUID(), nullable=True),
    sa.Column('agreed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('platform_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pro_payout_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time_slot', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_by', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("cancellation_by IN ('customer','pro','admin')", name='chk_booking_cancellation_by'),
    sa.CheckConstraint("payment_method IN ('cash','momo','card')", name='chk_booking_payment_method'),
    sa.CheckConstraint("payment_status IN ('unpaid','deposit_paid','paid','refunded','disputed')", name='chk_booking_payment_status'),
    sa.CheckConstraint("payout_status IN ('pending','disbursed','held','refunded')", name='chk_booking_payout_status'),
    sa.CheckConstraint("status IN ('confirmed','in_progress','completed','cancelled','disputed')", name='chk_booking_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pro_id'], ['pro_profiles.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('gateway_status', sa.String(length=50), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('momo_network', sa.String(length=10), nullable=True),
    sa.Column('payer_momo_number', sa.String(length=20), nullable=True),
    sa.Column('callback_received', sa.Boolean(), nullable=True),
    sa.Column('callback_at', sa.DateTime(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gateway IN ('paystack','cash')", name='chk_payment_gateway'),
    sa.CheckConstraint("momo_network IN ('mtn','telecel','at')", name='chk_payment_momo_network'),
    sa.CheckConstraint("status IN ('pending','success','failed','refunded')", name='chk_payment_status'),
    sa.CheckConstraint("type IN ('deposit','full_payment','refund')", name='chk_payment_type'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewee_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='chk_review_rating'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('bookings')
    op.drop_table('quotes')
    op.drop_table('service_requests')
    op.drop_table('pro_subcategories')
    op.drop_table('pro_service_areas')
    op.drop_table('pro_categories')
    op.drop_table('user_locations')
    op.drop_table('service_subcategories')
    op.drop_table('pro_profiles')
    op.drop_table('notifications')
    op.drop_table('geocode_cache')
    op.drop_table('admin_actions')
    op.drop_table('users')
    op.drop_table('service_categories')
    op.drop_table('location_index')
    # ### end Alembic commands ###
