"""add started_at and payout_disbursed_at to bookings

Revision ID: fa5e66e9ef5a
Revises: 7358f0a5b411
Create Date: 2026-06-26 11:17:34.674949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5e66e9ef5a'
down_revision = '7358f0a5b411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payout_disbursed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payout_disbursed_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
